---
title: "hw2_p8105"
author: "Chenshuo Pan"
date: "2023-09-26"
output: github_document
---

# Question1:

```{r,message=FALSE,warning=FALSE}
library(tidyverse)
library(dplyr)
library(readxl)
```

```{r}
#read dataset
pols_month <- read.csv("./data/pols-month.csv")
snp <- read.csv("./data/snp.csv")
unemployment <- read.csv("./data/unemployment.csv")
```

```{r}
pols_month_clean <- 
  pols_month%>%
  janitor::clean_names()%>%
  separate(col = mon , into = c('year','month','day'),sep = '-',convert = TRUE)%>%
  mutate(month = month.name[month])%>%
  mutate(president = case_when(
      prez_dem == 1 ~ "dem",
      prez_gop == 1 ~ "gop"
    ))%>%
  select(-prez_dem, -prez_gop,-day)%>%
  mutate(date = paste(year,month,sep = "-"))
```


```{r}
snp_clean <- 
  snp%>%
  janitor::clean_names()%>%
  separate(col = date , into = c('month','day','year'),sep = '/',convert = TRUE)%>%
  mutate(month = month.name[month])%>%
  mutate(year = case_when(
    between(year, 0, 15) ~ year + 2000,
    between(year, 50, 99) ~ year + 1900,
    TRUE ~ year))%>%
  relocate(year,month)%>%
  arrange(year,match(month,month.name))%>%
  mutate(date = paste(year,month,sep = "-"))
```

```{r}
unemployment_clean <- 
  unemployment%>%
  pivot_longer(cols = Jan:Dec,names_to = 'month',values_to = 'percent')%>%
  mutate(date = paste(Year,month,sep = "-"))
```

```{r}
combine_table <- inner_join(snp_clean,pols_month_clean,by = "date")%>%
  inner_join(unemployment_clean,by = 'date')
```

# Question2:
```{r}
#load the trash, professor, gwynnda sheet
trash <- read_excel("./data/202207 Trash Wheel Collection Data.xlsx",
                    sheet = 'Mr. Trash Wheel',
                    range = "A2:N549",
                    col_names = TRUE
                    )

professor <- read_excel("./data/202207 Trash Wheel Collection Data.xlsx", 
                        sheet = 'Professor Trash Wheel',
                        range = "A2:M96",
                        col_names = TRUE)

gwynnda <- read_excel("./data/202207 Trash Wheel Collection Data.xlsx", 
                      sheet = 'Gwynnda Trash Wheel',
                      range = "A2:K108",
                      col_names = TRUE)
```

```{r}
trash_clean <- trash%>%
  janitor::clean_names()%>%
  mutate(homes_powered = weight_tons * 500 / 30,
         wheel_name = "Mr")
```


```{r}
professor_clean <- professor%>%
  janitor::clean_names()%>%
  mutate(homes_powered = weight_tons * 500 / 30,
         wheel_name = "professor")
```

```{r}
gwynnda_clean <-gwynnda%>%
  janitor::clean_names()%>%
  mutate(homes_powered = weight_tons * 500 / 30,
         wheel_name = "gwynnda")
```

```{r}
combine_wheel <- gwynnda_clean%>%
  bind_rows(professor_clean)%>%
  bind_rows(trash_clean%>%mutate(year = as.numeric(year)))
```

# Question3:

```{r}
baseline <- read.csv("./data/MCI_baseline.csv",
                      skip = 1,
                     na.strings = c("."))
  
```


```{r}
baseline_clean <- baseline%>%
  janitor::clean_names()%>%
  mutate(sex = case_when(
      sex == 0 ~ "Female",
      sex == 1 ~ "Male"
    ),
    apoe4 = case_when(
      apoe4 == 0 ~ "APOE4 non-carrier",
      apoe4 == 1 ~ "APOE4 carrie"
    ))%>%
  filter(!is.na(age_at_onset))
```

